### ISSUE TITLE
Copying React Photo Gallery component

### ISSUE THREAD

**Issue by neptunian** [benhowell/react-grid-gallery#11]
It looks like you've copied my entire codebase with little changes that could have been pull requested and are trying to pass off this component as yours.  You need to take this repo down.

**Comment by benhowell** [comment]
Hi Sandy,
As I stated in my reply to you in your takedown request...

Looks like the parts of your code which happen to be the same as mine (openLightbox, closeLightbox funcs, etc.) are also identical to those in the react-images demo from which I based my gallery. I have acknowledged @jossmac for that but I will now make a clearer and more explicit attribution to @jossmac for the exact sections of code having looked back into it.

Unless the gallery originally published by @jossmac was originally your work, I shall regard your accusation as spurious.

Regards,
Ben.

**Comment by benhowell** [comment]
And whilst I didn't want to have to state the bleeding obvious (having now thoroughly looked through your library), I feel as if I have no choice but to, so here goes....

Did you even read the code or look at the demo or even read about the feature set and options? How is it even possible that I've, quote: "copied my entire codebase with little changes that could have been pull requested and are trying to pass off this component as yours"?

Did you even read the code or look at the demo or even read about the feature set and options? Because if you did, you would realise that react-grid-gallery uses a completely different mechanism for building justified rows. Not only that, here's a quick rundown of some of the "little changes" (as you call them) that set react-grid-gallery apart from your library (also, you can check out the project [demo page](https://benhowell.github.io/react-grid-gallery/) and [CHANGELOG](https://github.com/benhowell/react-grid-gallery/blob/master/CHANGELOG.md) sometime):

Image selection and tagging:

* Image tagging functionality. Optional `tags` prop takes an array of objects containing tag attributes. `value` prop is the text shown on the tag and `title` prop is the text shown when hovering over the tag. e.g. `tags: [{value: "Ocean", title: "Ocean"}, {value: "People", title: "People"}]`
* `onImageSelected` prop function now takes two optional args, index (index of selected image in images array) and image (the selected image object).
* Optional `onImageSelected` prop added. This prop takes a function and an optional image object as a parameter.
* Construction of thumbnail images and image rows removed from render. Thumbnails and rows now only rebuilt when container size changes.
* `selectedImages` state now set via props change.
* `onSelectedImagesChange` callback now called directly from `onToggleSelected`. Previously, a combination of setting `selectedImages` state and triggering `onSelectedImagesChange` inside `componentWillUpdate` caused a double render.
* Conditional to ensure image onClick not fired when no function specified
* Option to allow disabling of lightbox image display. `enableLightbox` (PropType.bool, default `true`)
* Option to allow passing in of function to execute on thumbnail click. `onClickThumbnail` (PropType.func, default `openLightbox`)
* Removed darkening effect on thumbnail hover when `enableImageSelection: false`
* Enabled preloadNextImage option from [react-images](https://github.com/jossmac/react-images/)
* Support for disabling image selection (optional)
* Support for all functional lightbox options
* Shrinkage effect on thumbnail selection
* Darkening effect on thumbnail hover (increases visibility of check button)
* Pointer cursor on thumbnail hover
* Auto scaled, clipped and justified images to fit rowHeight prop


I have now spent way too much time on this idiotic issue so I shall now bid you good day sir. 
Good day sir.

**Comment by benhowell** [comment]
Reopening this issue as I've had an email asking me about a thread posted on HN: https://news.ycombinator.com/item?id=12332411

The same allegations have been made on reddit, in email to me directly, in issues and pull requests such as: [this](https://github.com/benhowell/react-grid-gallery/pull/3) and [this](https://github.com/benhowell/react-grid-gallery/pull/3/commits/c54081de384c4f9221329b3c8932713900b9d651)

I don't know if there's actually multiple people out there that care enough to make the same spurious allegations, or if it's jealousy, sour grapes or a genuine case of Dunning-Krueger, however, allow me to reiterate that I completely and utterly stand by my statement above and it frustrates me no end to be still dealing with baseless, malicious allegations years down the track.

I'm sharing react-grid-gallery because I think others might find it useful. I wrote react-grid-gallery because I couldn't find anything that suited my needs. It's libre! Take it, do what you want with it. Enjoy it.
