### ISSUE TITLE
When inside a modal, pressing Escape from lightbox closes the modal

### ISSUE THREAD

**Issue by mihaimartalogu** [benhowell/react-grid-gallery#115]
When the gallery is instantiated inside a modal, closing the lightbox with Escape also closes the modal. Is there a workaround for this?

### Expected behaviour
Escaping from the lightbox should only close the lightbox

### Actual behaviour
The Escape event seems to continue propagation, therefore the containing modal gets closed as well.

### Steps to reproduce behaviour
https://codesandbox.io/s/6zpxpnz82n

### Operating system
Linux

### Browser and version
Google Chrome | 70.0.3538.102 (Official Build) (64-bit)

**Comment by benhowell** [comment]
This is a problem with react-images (the library used in react-grid-gallery for the lightbox). The specific issue is this: https://github.com/jossmac/react-images/issues/251

You can confirm this behaviour in https://codesandbox.io/s/6zpxpnz82n by clicking on the lightbox image after it has opened and then hitting escape (modal doesn't close because it no longer has focus).

**Comment by mihaimartalogu** [comment]
Thanks for the pointer to the underlying problem.

I figured out a workaround by setting focus to the body in lightboxWillOpen:
```javascript
lightboxWillOpen={() => {
  document.body.focus();
  document.activeElement.blur();
}}
```
Although the full workaround is a bit convoluted as some additional hacks are needed to make everything work (see https://codesandbox.io/s/v8vj706wl), I'll be using this for now.
