### ISSUE TITLE
Unable to close Lightbox using Esc or cross button

### ISSUE THREAD

**Issue by jibinpt** [benhowell/react-grid-gallery#12]
Hi,

Thanks for building such an amazing module. While trying to make use of this module, I am unable to close the Lightbox using Esc or cross button

**Comment by benhowell** [comment]
Wow, thanks for the praise!
Can you post the section of code where you're specifying your options?

**Comment by jibinpt** [comment]
Other features such as left arrow and right arrow works.

Tag which I used:
<Gallery images={IMAGES}/>

 I am getting the following error in web console:

Uncaught TypeError: Cannot read property 'componentWillLeave' of undefined

**Comment by benhowell** [comment]
Hmm, ok.
What browser are you using?

Can you do me a favour and check to see if you can close using esc and close button on the demo page? https://benhowell.github.io/react-grid-gallery/

Thanks...

**Comment by jibinpt** [comment]
I am using chromium. ESC and close button works on the demo page

**Comment by benhowell** [comment]
I've tested in chromium and can't reproduce the problem. Is it possible you're using a different version of react, react-dom or react-images than what's in the package.json file? 

If that's not the case, can you point me to your code repository or attach your code file and I'll take a closer look.

**Comment by jibinpt** [comment]
I was using different version for react and react-dom. I was using 
```
"react": "^0.14.6",
 "react-dom": "^0.14.6",

```Changing it to the version specified in package.json of your repo solved the issue. What has to be done to make your repo compatible with the above specified versions of react and react-dom?

**Comment by benhowell** [comment]
I wrote react-grid-gallery from the beginning using react and react-dom >=15.3.0 so I'm not sure what breaking changes were made between 0.14 and 15 because I didn't need to deal with them. 

The error you're seeing could also stem from [react-images component](https://github.com/jossmac/react-images) which is a dependency of this component and which also requires react and react-dom >=15.3.0.

I'm glad you've managed to solve the issue ;-)
