### ISSUE TITLE
Legacy Context API causing errors

### ISSUE THREAD

**Issue by IVainqueur** [benhowell/react-grid-gallery#172]
**ERROOOOOR**

> Warning: Legacy context API has been detected within a strict-mode tree.
> 
> The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
> 
> Please update the following components: Lightbox, Portal
> 
> Learn more about this warning here: https://reactjs.org/link/legacy-context
>     at Lightbox (http://localhost:3000/static/js/bundle.js:74420:5)
>     at div
>     at Gallery (http://localhost:3000/static/js/bundle.js:48550:5)
>     at div
>     at _Gallery (http://localhost:3000/static/js/bundle.js:1768:5)
>     at section
>     at AccomodationSections (http://localhost:3000/static/js/bundle.js:1172:5)
>     at main
>     at div
>     at Accomodation (http://localhost:3000/static/js/bundle.js:2792:74)
>     at Routes (http://localhost:3000/static/js/bundle.js:183650:5)
>     at Router (http://localhost:3000/static/js/bundle.js:183583:15)
>     at BrowserRouter (http://localhost:3000/static/js/bundle.js:182392:5)
>     at App

Would really appreciate if the library was updated to the latest everything cz I can't be the only one who is annoyed by errors in the console 😅

**Comment by itoldya** [comment]
Hello @IVainqueur 👋 Thank you for creating an issue! 

It's really a problem for us now. We've started discussion [here](https://github.com/benhowell/react-grid-gallery/discussions/179) and really appreciate it if you join. In short, we can't control the sources of the `Lightbox` component since it's a third-party dependency. And we are considering completely removing lightbox functionality to become more flexible in the future.

**Comment by itoldya** [comment]
no more warnings (as well as Lightbox) since the v1.0.0 resealed
