### ISSUE TITLE
How does one implement eg on click image in gallery,  open link instead of lightbox ? Thanks

### ISSUE THREAD

**Issue by GuacheSuede** [benhowell/react-grid-gallery#18]

**Comment by benhowell** [comment]
Use the lightbox option: `onClickImage` https://github.com/benhowell/react-grid-gallery#lightbox-options

**Comment by pztrick** [comment]
I ended up finding it easiest to sub-class `Gallery` and override `onClickImage` directly so that I would have access to `this.state.currentImage` (rather than passing through parent->child `props` as indicated in docs).

```
class CustomGallery extends Gallery {
    onClickImage(e) {
        var image = this.state.images[this.state.currentImage];
        window.location.href = image.detailUrl;
    }
}
```

Then use `<CustomGallery {...props}/>` in place of `<Gallery/>` in your React component. The `detailUrl` attribute was just another attribute I added to the `images` property array items.
