### ISSUE TITLE
Would be nice to be able to pass tile viewport styles?

### ISSUE THREAD

**Issue by daddycoder0** [benhowell/react-grid-gallery#29]
Very useful gallery :)

Would love to be able to provide bespoke tileViewportStyle function (or some other means of setting selected and unselected styles), as well as being able to disable the tick icons?

**Comment by benhowell** [comment]
You can remove the tick icons by setting the option `enableImageSelection` to `false`, but the first part of your question leads me to believe that that isn't quite what you're after. 

I get the impression that you want to be able to select thumbnails by clicking on them (rather than on the tick icon) and style how selected and non selected thumbnails look? 

Perhaps you can give me a clearer picture of what you want to do?

**Comment by daddycoder0** [comment]
That is exactly right - I was already able to disable the lightbox with the existing params. I would like to be able to select one or multiple images to perform an action on, and the current style of the tile viewport when selected doesn't fit with my theme.

**Comment by benhowell** [comment]
Ok, I'll look into it when I can :+1:

**Comment by benhowell** [comment]
Fixed in [v0.4.0](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.4.0)
