### ISSUE TITLE
Component renders nothing when used inside a modal

### ISSUE THREAD

**Issue by iMerica** [benhowell/react-grid-gallery#37]
Hi,

I've included this component inside a modal. Everything else mounts properly in my modal except for this component. The only way I can force it to render is by resizing the window or forcing a state change in the Chrome inspector. Here's a quick glance what the state of the component looks like by default after the page has loaded.

![screen shot 2017-07-26 at 1 46 44 am](https://user-images.githubusercontent.com/487897/28612527-744feb42-71a4-11e7-8f9f-ac390de42949.png)

Any ideas to work around this?

**Comment by iMerica** [comment]
I suspect this is happening because at render time `containerWidth` is 0 (because it's a modal, AKA it has no width until it displays.

**Comment by benhowell** [comment]
Are you sure the component isn't mounting? Even with a container width of zero, the component should mount, albeit with a width of zero because the width of the gallery is determined by the container in which you embed it.

To your previous comment, I can see why resizing the window makes the gallery appear IFF the component does mount. `onResize()` handler (which triggers a render) is listening to the window resize event. Resizing based upon changes to the parent container size is not straight forward and there exists no standard for element resize events at this time.

**Comment by iMerica** [comment]
Good point. It renders, but it's empty (see below).  I've re-named the issue.


![screen shot 2017-07-26 at 2 53 25 am](https://user-images.githubusercontent.com/487897/28615397-bb2a2236-71ad-11e7-95b8-f7eef081efe4.png)

**Comment by iMerica** [comment]
I've forked this project and I'm going to investigate achieving the same output without needing to know the container width at all.

**Comment by benhowell** [comment]
You could also use the react `component.forceUpdate(callback)` method to force a re-render of react-grid-gallery when your modal is shown. Not sure what events/callbacks your modal has but if you know when it has been shown you should then be able to call `myReactGridGallery.forceUpdate()` to render the component.

**Comment by iMerica** [comment]
Thanks for your help @benhowell. I was able to fix this by adding a small time out to the modal. In my case, the modal's animation to ease-in was causing a race condition.

e.g:
```js
class MyComponent extends React.Component {
  
  toggleModal = () => {
    setTimeout(() => {
      this.forceUpdate()
    }, 500)
  }
    
 render(){
  return (
    <div>
      <a onClick={this.toggleModal} href="#">TRIGGER MODAL</a>
      <MyModal>
        <Gallery
          //..props
        />        
      </MyModal>
    </div>
   );
  }
}
```

**Comment by benhowell** [comment]
Excellent! I'm glad you found a solution :+1:
