### ISSUE TITLE
html thumbnail captions

### ISSUE THREAD

**Issue by micahstubbs** [benhowell/react-grid-gallery#71]
feature request: support for html thumbnail captions.  

I'd like to be able to pass a string of html in as the value of the caption parameter and see my custom html rendered under the image in detail view.

**Comment by benhowell** [comment]
Lightbox (detail view) is provided by [react-images](https://github.com/jossmac/react-images). You can use the `customControls` prop to render html _above_ the image but at this point in time, there seems to be no way to set another place for these to render. This issue is mentioned here: https://github.com/jossmac/react-images/pull/130

**Comment by micahstubbs** [comment]
interesting.  thanks for sharing the context 😄
