### ISSUE TITLE
Wrong index on onSelectImage

### ISSUE THREAD

**Issue by rschlack** [benhowell/react-grid-gallery#89]
Seem on my mac, across all browsers, when I click the second image on the second row it skips a number in the index.  As I change screen widths it always affects that second row, second image.  It skips a number and returns the information for the next image.  I've duplicated this with the samples.

Rob

**Comment by benhowell** [comment]
I can't reproduce the bug you've described, which is odd to say the least. I don't have a mac so I'm unable to test your specific case.

**Comment by benhowell** [comment]
Those keys are made with the image src prop in the place where you're
seeing "undefined" so it seems as if whatever the src prop is on the image
object that that thumbnail is a part of, isn't set. I can't see how that is
caused within react-grid-gallery because all it does is read the props.
Whether or not the thumbnail and src URLS exist or are correct or valid is
outside the library's control.

**Comment by rschlack** [comment]
It seems like that except I'm using your Demo1.js code with no changes and I still see the issue.  I've gotten the module to work correctly in both a new react project and a new meteor project.  I've even downgraded React to 15 and it still works.  Must be some npm module that is somehow conflicting with your code that generates the thumbnails.  I can see all the images, it just sticks in an extra node into the array with an undefined image and it changes spots as you make the browser window bigger and smaller.  If I reduce the browser window so only 1 image shows on a row than the undefined image is between the 2nd and 3rd image.

**Comment by rschlack** [comment]
Figured it out.  An Array.prototype was messing with your arrays.  Sorry for the trouble.

**Comment by benhowell** [comment]
No worries, thanks fir the update :+1:
